package com.joyhsin.hotspot;
import jakarta.validation.Valid; import java.io.IOException; import java.util.*;
import org.springframework.core.io.Resource; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile;
@RestController
public class SceneController {
 private final SceneService scenes; private final ImageStorageService images; public SceneController(SceneService s,ImageStorageService i){scenes=s;images=i;}
 @GetMapping("/api/scenes") List<SceneData> list(){return scenes.list();} @PostMapping(value="/api/scenes",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) SceneData create(@RequestParam String name,@RequestPart MultipartFile image){return scenes.create(name,image);} @PostMapping("/api/scenes/sample") SceneData sample(){return scenes.sample();}
 @GetMapping("/api/scenes/{id}") SceneData get(@PathVariable String id){return scenes.get(id);} @PutMapping("/api/scenes/{id}/draft") SceneData draft(@PathVariable String id,@Valid @RequestBody SceneData.DraftRequest req){return scenes.draft(id,req.hotspots());} @PostMapping("/api/scenes/{id}/publish") SceneData publish(@PathVariable String id){return scenes.publish(id);} @DeleteMapping("/api/scenes/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void delete(@PathVariable String id){scenes.delete(id);}
 @GetMapping("/uploads/{name}") ResponseEntity<Resource> upload(@PathVariable String name) throws IOException {Resource r=images.load(name);return ResponseEntity.ok().contentType(MediaType.parseMediaType(Optional.ofNullable(java.nio.file.Files.probeContentType(r.getFile().toPath())).orElse("application/octet-stream"))).body(r);}
 @GetMapping("/api/products") List<SceneData.Product> products(@RequestParam(defaultValue="") String q){var all=List.of(new SceneData.Product("POS-01","双屏智能 POS","¥2,999","/sample/products/pos.svg","收银、会员与订单聚合","https://example.com/products/pos"),new SceneData.Product("NET-02","企业级 Wi-Fi 6","¥1,299","/sample/products/wifi.svg","稳定无线覆盖","https://example.com/products/wifi"),new SceneData.Product("BOT-03","智能送餐机器人","¥19,999","/sample/products/robot.svg","自动规划送餐路线","https://example.com/products/robot"),new SceneData.Product("DSP-04","商用数字标牌","¥3,699","/sample/products/screen.svg","远程更新数字菜单","https://example.com/products/screen"));String x=q.toLowerCase();return all.stream().filter(p->(p.code()+p.name()+p.description()).toLowerCase().contains(x)).toList();}
}
